### ISSUE TITLE
The UML image on the README page shows an error

### ISSUE THREAD

**Issue by pstavirs** [markushedvall/plantuml-encoder#7]
Probably something on the plantuml.com side of things - not sure if transient or permanent, but the UML diagrams are not being generated - see the README page of this project for an example.

**Comment by imyelo** [comment]
+1 here.

I forked the new compressing codes from PlantUML website temporarily. Hope it help.

https://github.com/imyelo/docsify-plantuml/blob/master/src/compress.js

**Comment by markushedvall** [comment]
Fixed in pull request https://github.com/markushedvall/plantuml-encoder/pull/8
part of release 1.2.5
